### ISSUE TITLE
Proposal for milestone 1

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#111]
To have a common goal in development I would like to propose a first milestone. In the first milestone the node implementation these features are implemented:

- [ ] users can upload packages
    - [x] check permissions
    - [x] validate package
    - [ ] install libraries (reject content that won't work because user doesn't have permissions to install libraries)
    - [x] add content to storage
- [ ] users can perform CRUD operations on content
    - [x] create
        - [ ] temporary file uploads work
        - [ ] copy & pasting works (seem to require server side support for cloning image files and the like)
    - [x] display content
    - [ ] download content
    - [x] update
        - [ ] atomic operations of updates (= deleting an image and not saving the content shouldn't permanently delete the image)
        - [ ] copy & pasting works
     - [ ] delete
- [x] the site gets content type updates from the H5P hub

**Comment by JPSchellenberg** [comment]
That looks good. Would you also say that this reached milestone should be v1.0.0 (first production ready release)?

**Comment by sr258** [comment]
If we want to follow the traditional semantic versioning approach, I think 1.0 should include more. However, if we want to regularly publish new versions like Chrome, v1 fine.

**Comment by sr258** [comment]
I have added the missing issue for the features we haven't done yet and introduced a proper milestone.
